### PR TITLE
Change Twig autoescape to true

### PR DESCRIPTION
**Pull request by kenjis**
I want to propose this change. 

Because
- Twig's default is true, so no wonder to Twig users
- It is safer for preventing XSS. Secure by default

Is there something wrong with it?

### CODE REVIEW

**Comment by koriym** [comment]
> It is safer for preventing XSS. Secure by default

Is it ? Yes it is in some context. I also know there are those who believe as you said.
But "implicit escape" vs "explicit escape" argument seems controversial to me. Why template engine X has "implicit" as default and other Y has opposite ? 

We have three template engine adapter so far. Aura.View, Smarty and Twig. Only one has different default. (also native PHP templates are the inability to auto-escape variables properly).

A framework as a higher level module , it does not want to depend on low-level modules (adapter's implementation) as much as they can. Details (template engine adapter) should depend on common abstractions.

What will be happened if we will set another escaping mechanism not in template engine layer ? We need to care about only for twig adapter.

For me, explicit binding to specifying a media type seems more professional sometime. But I'm not trying to convince you as "Hey, this is a better way, YOU SHOULD DO THIS". No. I really don't like that way.

My personal opinion is NOT important here. It's more important the fact **this topic is controversial.** then I think ok let's behave like others as default.

I may be wrong. It's nice to have more voices here.

> Twig's default is true, so no wonder to Twig users

Agreed.

**Comment by mackstar** [comment]
We need to be able to pass this value in from a configuration whilst providing a sensible default. Having the ability to add something like the following in named params would be a good way of doing it?

```
[
    'twig' => [
         'locations' => ['/var/www/templates', '/var/lib'],
         'cache' => $this->tmpDir . '/twig/cache',
         'debug' => true,
         'autoescape' => false 
    ]
];
```

We can then pass the values though...

**Comment by koriym** [comment]
Thanks @mackstar, That way is seems quite reasonable and most framework do.  (Also we do same in some in db setting.)

But I think we need to be more careful for this way ?  Because ...
1. We are defining which config values should be prepared.
2.  maintenance for 1
3. We need documentation about which values are prepaid and how named.
4. maintenance for 3

the `provider` binding seems more free and clean. They can `new` and edit as described in manual. Unnecessary to care about how defined BEAR.Sunday.

## 

Or missing the point ?

**Comment by mackstar** [comment]
The main difference I see it that we have these as optional parameters - if you do not add them we choose these for you. We **do need this level of control** or otherwise nearly all providers need to be rewritten for each project.

Can you think of another way of doing this?

**Comment by kenjis** [comment]
> For me, explicit binding to specifying a media type seems more professional sometime.

Yes. Twig `autoescape` is escaping only for HTML. So it is nonsense and/or harmful to other media types.

**Comment by mackstar** [comment]
@koriym Rewriting providers is still cumbersome a process for most people - a hurdle for newcomers I believe. But you do have a valid point.

**Comment by koriym** [comment]
@mackstar yeah, I see. I think this topic can be thinkable with another aspect.

> nearly all providers need to be rewritten for each project.

Even so, we can reuse it.
`ExciteTwigProvider` will be placed in `ExciteModule` which may holds all customized module for Excite. It is handy. Static config file does not have this level of re-useability ?

**Comment by koriym** [comment]
What about `addFunction` or `addFunction` ? if we move to this functionality to config file,We need more BEAR.Sunday specific configuration on each `addX`. Even Symfony doesn't seem doing very well for this.
http://twig.sensiolabs.org/doc/advanced_legacy.html#creating-an-extension

**Comment by koriym** [comment]
I have one experience with newcomer. I tell her that copy original provider and put `My` prefix and modify it. She was happy with this '`copy-paste-and-modify` rule because she only needs this single rule for any modification and no need to search document.

**Comment by mackstar** [comment]
I think it is a good point and I can be happy with this. However it needs to be more obvious in the documentation....

**Comment by koriym** [comment]
@mackstar Yeah, Right. @kenjis is now heavily contributing for documentation and I think we are in the stage.  I will ask more people and get feedback. Fortunately I have more newcomer now.

**Comment by koriym** [comment]
@kenjis I'm still not convinced that things are not simple as you described.

I found very insightful article about **automatic escaping** by Padraic Brady. Please take a look.

http://blog.astrumfutura.com/2012/06/automatic-output-escaping-in-php-and-the-real-future-of-preventing-cross-site-scripting-xss/

Rob Allen summarized this article nicely.

> In the game of mitigating against the risks of XSS, how you escape is not as important as knowing why you are escaping. That second point, understanding why you escape data on output, is unfortunately commonly misunderstood. Yet, without that basic understanding – your choice of how to escape is quite possibly incorrect and, worse, it allows insecure escaping practices to thrive as that misunderstanding becomes embedded in what we pass on to other PHP programmers. We’re self-perpetuating our own ignorance

http://akrabat.com/around-the-web/automatic-output-escaping-in-php-and-the-real-future-of-preventing-cross-site-scripting-xss-padraic-brady/

**Comment by koriym** [comment]
A friendly reminder: 
I'm not on anti-auto-escaping side. I'm just trying not to judge every controversial topic and impose "right-way" to the others.  BEAR.Sunday is **not** [omakese](http://david.heinemeierhansson.com/2012/rails-is-omakase.html).

**Comment by koriym** [comment]
I’m concerned more about this..

> Twig's default is true, so no wonder to Twig users

**Comment by kenjis** [comment]
Yes, this is not so simple.

I've found the name `autoescape` is not good. Because it implies auto vs manual, autoescape escapes all variables correctly.

But the truth is that (Twig) autoescape could not prevent all XSS automatically. It is just default escaping strategy.

> It is safer for preventing XSS. Secure by default

I believe it is safer, but I don't say it is safe.

**Comment by koriym** [comment]
Seems missing the point. We are not discuss about the perfection ?

**Comment by koriym** [comment]
@kenjis I found most user need to provide their own Twig provider to have their own custom helper. So this issue seems not really matter. I will close this. But thank you for the long discussion and feel free to re-open this issue to provide further information.

**Pull request closed without merging**
