### PR TITLE
Add CSRF protection to AuraForm with Aura.Session

### PR DESCRIPTION
**Pull request by kenjis**
Add Aura.Session and CSRF protection to AuraForm.

This is my first attempt to add CSRF protection. If there is something wrong, please tell me.

### CODE REVIEW

**Comment by koriym** [comment]
@jingu Thoughts ?

**Comment by kenjis** [comment]
Travis CI build failed because of coding style (trailing_spaces). So fixed.

**Comment by jingu** [comment]
I thought it should be merged 👍

**Comment by kenjis** [comment]
Fixed.

**Pull request merged**
