### PR TITLE
Environment check script die, run without PDO

### PR DESCRIPTION
**Pull request by MugeSo**
Shouldn't die if `DB Connect` is surely _Optional_.

### CODE REVIEW

**Comment by koriym** [comment]
Thanks for the PR.

But this PR make me re-think about db connection check. Do we need it ?
- That's application concern, not a package concern.(id / password)
- We need before because we use mysql connection for Sandbox application. but now we use sqlite. Mysql installation is completely optional.

Your thought ? cc/ @mackstar

**Comment by mackstar** [comment]
I think this whole code can be simplified anyway. In spout I added the following to Spout/Admin's  `test/bootstrap.php`

```
$GLOBALS['DB'] = DriverManager::getConnection($config['master_db']);
```

This simplifies the DB connection code for testing and means we can have a choice of databases. There should also be no need to do a check.

**Comment by koriym** [comment]
That's the point.
I also found people feel _not so good_ some optional stuff is `NG` even they don't  need it.

**Comment by MugeSo** [comment]
> I also found people feel not so good some optional stuff is NG even they don't need it.

:+1:

Then close this issue and do review in new issue, right?

**Pull request closed without merging**
