### PR TITLE
Adding TWIG template-ing through file system.

### PR DESCRIPTION
**Pull request by mackstar**
I have also added bootstrap.css where needed for debugging.

### CODE REVIEW

**Comment by koriym** [comment]
We also need to provide these plugins.
https://github.com/koriym/BEAR.Package/tree/develop/src/BEAR/Package/Provide/TemplateEngine/Smarty/plugin

**Comment by mackstar** [comment]
Yes I think `lib_dir` is better. Let's do that!

**Comment by mackstar** [comment]
I also need to work out the best way of adding `twig` plugins, but I will do that as I use it in `Spout`.

**Comment by koriym** [comment]
Still Smarty is default in sandbox, Everything should work.

**Pull request merged**
