### PR TITLE
Symfony Routerをつけました。

### PR DESCRIPTION
**Pull request by mackstar**
AppModuleに  
        $this->install(new ProvideModule\Router\SymfonyRouterModule($this));
        $this->bind()->annotatedWith('routes_file_location')->toInstance(BearBase\App::DIR);

をすれば、APPDIR/routes.ymlファイルでSymfony Routesは動きます。

$app->router->match();

だけで行けます。setGlobalsを使っていません（SymfonyのHttp Foundationはその動きをしてくれます）。

### CODE REVIEW

**Comment by koriym** [comment]
@mackstar Great PR.thanks. Can the dependency inside SymfonyRouter router be injected ? (such as FileLocator

**Comment by mackstar** [comment]
Good idea, I will do that! Which other dependencies do you feel should be injected?

**Comment by mackstar** [comment]
Also the Travis build fails because of an Aura
 dependency. Do you know why that is?

**Comment by koriym** [comment]
Any dependency which does _not_ accepts dynamic parameter(dependency) in constructor, such as time, web context($_SEVER) or Request object.

> Which other dependencies do you feel should be injected?

YamlFileLoader seems to be one. It has a dependency, Use [Provider Binding](http://code.google.com/p/rayphp/wiki/ProviderBindings). Hope it goes straight.

**Comment by koriym** [comment]
I will take a look for travis error.

..maybe their problem, lets try later.

**Comment by koriym** [comment]
instead of _Pulling_ dependency($GLOBAL) from web context object (even with static method)

``` php
$request = Request::createFromGlobals();
```

what about the way like this ?

``` php
    public function setGlobals($globals)
    {

        $request = new Request(
            $globals['_GET'],
            $globals['_POST'],
            [],
            $globals['_COOKIE'],
            $globals['_FILES'],
            $globals['_SERVER']
        );
        parse_str($request->getContent(), $data);
        $request->request = new ParameterBag($data);
        $context = new RequestContext;
        $context->fromRequest($request);
        $get = $request->query->all();
        $post = $request->request->all();
        $context->setParameters(array_merge($get, $post));
    }
```

We can pass all environment value to Symfony\Component\HttpFoundation\Request constructor in parameter. 

No need to rewrite, (Symfony "Request" does not seems so well designed in this way. ちょっと面倒?)
Just want to share the idea of coding style.

**Comment by mackstar** [comment]
Ok yes, I was also wondering about that. I will have another look on the plane on my way there.

Thanks...

**Comment by koriym** [comment]
Take care, have a nice flight !

**Comment by koriym** [comment]
We can inject  application directory path with "AppDirInject" trait.

``` php
use AppDirInject;

protected configure()
{
    $this->install(new ProvideModule\Router\SymfonyRouterModule($this));
    $this->bind()->annotatedWith('routes_file_location')->toInstance($this->appDir);
}

```

**Pull request merged**
