### PR TITLE
A lame syntax fix - sorry!

### PR DESCRIPTION
**Pull request by mackstar**

### CODE REVIEW

**Comment by koriym** [comment]
Maybe we need two provider ? `TwigProvider` and `DevTwigProvider`.

**Comment by koriym** [comment]
Another question: Please let me know if there is any way to detect new plugin and install it . Or do we need `addExtension` on each addition ?

With Smarty, Specified plugin dir is scanned and installed it.

**Comment by koriym** [comment]
Also ... I think its nice to have your voice about https://github.com/koriym/BEAR.Package/pull/132

**Comment by mackstar** [comment]
We also need a mechanism for having more Twig paths...

**Pull request merged**
