### PR TITLE
Add is_safe option to Twig "form" function for AuraForm

### PR DESCRIPTION
**Pull request by kenjis**
This Twig function outputs HTML form part. And Aura takes care of correctly escaped HTML generation.
So I add `is_safe` option to prevent Twig from escaping the function's output.

This fix makes us to be able to use the `form` function in Twig when `autoescape` is true.

### CODE REVIEW

**Comment by kenjis** [comment]
Any comments?

Without this fix, we have to add `|raw` to all `form` functions when autoescape is true. It's a pain!

```
{{ form(form['__csrf_token']['hint'])|raw }}
```

**Comment by mackstar** [comment]
I don't have any real problem with this.. 

I guess because this only affects Aura form components and nothing else that maybe it is okay. But when populating content into the form fields you need to remember to escape it (possibly)?

Having a sensible set of defaults is a good thing. 

I do have concerns that BEAR.Package is becoming too overloaded. I would like to see a stripped down version that can be used as a starting point. Then having each provider/module loaded as their own composer package?!

**Comment by kenjis** [comment]
> I guess because this only affects Aura form components and nothing else that maybe it is okay. 

Yes. This is a Twig function to generate input tags using Aura form.

> But when populating content into the form fields you need to remember to escape it (possibly)?

No, Aura takes care of them. 

`{{ form(<hint_array>) }}` generates input tag with escaped value.

But if we set Twig autoescape true, Twig escapes the output of the function. So we have to write `{{ form(<hint_array>)|raw }}`.

This PR make it possible to write `{{ form(<hint_array>) }}` even if we set Twig autoescape true.

**Comment by koriym** [comment]
Let me clarify again.

before PR
`{{ form(<hint_array>) | raw }}`

with PR
`{{ form(<hint_array>) }}`

with `autoescape` is on.

Correct ?

**Comment by kenjis** [comment]
@koriym Yes.

And I should have added the Twig's `is_safe` option at the first PR of the `form` function.
But I'm sorry, I forgot adding it.

You can see docs on Twig's `is_safe` option: 
http://twig.sensiolabs.org/doc/advanced.html#automatic-escaping
It is about filters, but it is the same with functions.

**Comment by koriym** [comment]
Thank you for the clarify for this @kenjis 

@mackstar I have a same feeling about "overloaded" and maybe it should be separate as more independent  package rather than put everything to `BEAR.Package`.  But to see only this issue, @kenjis 's PR seems fair.

**Pull request merged**
